package com.example.demo.rims;

public enum CabecerasRIMS {
	MOTIVO,DISCREPANCIA,TRADE,SENTIDO,ISIN,ERI,FECHA,HORA,CCI,TITULOS,BOLSA,MIEMBRO,CUENTA,CCC,PLATAFORMA,SEGMENTO,ORDENANTE,REFEXT,TRADE_TAG,COI,MERCADO,ESTADO,TITULAR
}
